AlwakeelAdminPanel/Areas/BlogsModels/Controllers/BlogsController.cs
using AlwakeelBusinessLayer.Implementation;
using AlwakeelDomainLayer;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlwakeelAdminPanel.Models;

namespace AlwakeelAdminPanel.Areas.BlogsModels.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BlogsController : Controller
    {
        Blog bl = new Blog();
        Business business = new Business();
        BusinessUsers businessUsers = new BusinessUsers();
        // GET: BlogsModels/Blogs
        public ActionResult Index()
        {
            ViewBag.Titles = " Blogs";
            if (User.IsInRole("Admin"))
            {
                List<BlogDomain> model = bl.Get().OrderBy(x=> x.blogDate).ToList();
                return View(model);
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                List<BlogDomain> model = bl.GetByPublish(business.GetById((int)Buser.BusinessId).BusinessNameEn).OrderBy(x => x.blogDate).ToList();
                return View(model);
            }
                
        }

        // GET: BlogsModels/Blogs/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.Titles = " Blogs";
            BlogDomain model = bl.GetById(id);
            return View(model);
        }

        // GET: BlogsModels/Blogs/Create
        public ActionResult Create()
        {
            ViewBag.Titles = " Blogs";
            BlogDomain model = new BlogDomain();
            string UserId = User.Identity.GetUserId();
            BusinessUserDomain Buser = businessUsers.Get(UserId);
            model.PublishBy = business.GetById((int)Buser.BusinessId).BusinessNameEn;
            model.blogDate = DateTime.Now;
            return View(model);
        }

        // POST: BlogsModels/Blogs/Create
      
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(BlogDomain model)
        {
            ViewBag.Titles = " Blogs";
            try
            {
                if (model.IamgeFile == null)
                {
                    return View(model);
                }
                // TODO: Add insert logic here
                model.blogIamgeUrl=UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.IamgeFile, "blog")), false);
                bl.Add(model);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

       

        // GET: BlogsModels/Blogs/Delete/5
        public ActionResult Delete(int id)
        {
            bl.Delete(id);
            return RedirectToAction("Index");
        }

        public  string AddImage(HttpPostedFileBase File, string Type)
        {
            string fileName = Path.GetFileNameWithoutExtension(File.FileName);
            string extension = Path.GetExtension(File.FileName);
            fileName = Type + DateTime.Now.ToString("yymmssfff") + extension;
            string imgname = "/Image/Blogs/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/Blogs"), fileName);
            File.SaveAs(fileName);
            return imgname;
        }




    }
}

AlwakeelAdminPanel/Areas/BlogsModels/Views/Blogs/Create.cshtml
@model AlwakeelDomainLayer.BlogDomain

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    textarea
    {

        height:20px
    }
</style>
<link href="~/assets/summernote/summernote.css" rel="stylesheet" />

@using (Html.BeginForm("Create", "Blogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.PublishBy)
    @Html.HiddenFor(model => model.blogDate)
    <div class="form-horizontal">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.blogTitleEn, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.blogTitleEn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.blogTitleEn, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.blogTitleAr, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.blogTitleAr, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.blogTitleAr, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-lg-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.blogBodyEn, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.blogBodyEn, new { htmlAttributes = new {  @rows = "20" } })
                   
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.blogBodyAr, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.blogBodyAr, new { htmlAttributes = new {  @rows = "20" } })
                 
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.blogIamgeUrl, htmlAttributes: new { @class = "control-label " })
                    <input type="file" id="IamgeFile" name="IamgeFile" required />
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/assets/summernote/summernote.js"></script>
@Scripts.Render("~/bundles/jqueryval")
<script>
    $(document).ready(function () {
        $('#blogBodyEn').summernote();
        $('#blogBodyAr').summernote();
    });
</script>

AlwakeelAdminPanel/Areas/BlogsModels/Views/Blogs/Details.cshtml
@model AlwakeelDomainLayer.BlogDomain

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-3">
        <label>@Html.DisplayNameFor(model => model.blogId)</label>
        <label class="form-control">@Html.DisplayFor(model => model.blogId)</label>
    </div>
    <div class="col-lg-3">
        <label>@Html.DisplayNameFor(model => model.blogTitleEn)</label>
        <label class="form-control">@Html.DisplayFor(model => model.blogTitleEn)</label>
    </div>
    <div class="col-lg-3">
        <label>@Html.DisplayNameFor(model => model.blogTitleAr)</label>
        <label class="form-control">@Html.DisplayFor(model => model.blogTitleAr)</label>
    </div>
    <div class="col-lg-3">
        <label>@Html.DisplayNameFor(model => model.PublishBy)</label>
        <label class="form-control">@Html.DisplayFor(model => model.PublishBy)</label>
    </div>

    <br />
    <hr />

    <div class="col-lg-3">
        <label>@Html.DisplayNameFor(model => model.blogDate)</label>
        <label class="form-control">@Html.DisplayFor(model => model.blogDate)</label>
    </div>
    <div class="col-lg-3">
        <label>@Html.DisplayNameFor(model => model.ViewsNuber)</label>
        <label class="form-control">@Html.DisplayFor(model => model.ViewsNuber)</label>
    </div>

    <br />
    <hr />
    <div class="col-lg-12">
        <label>@Html.DisplayNameFor(model => model.blogBodyEn)</label>
        <p>@Html.DisplayFor(model => model.blogBodyEn)</p>
    </div>

    <div class="col-lg-12">
        <label>@Html.DisplayNameFor(model => model.blogBodyAr)</label>
        <p>@Html.DisplayFor(model => model.blogBodyAr)</p>
    </div>
</div>

AlwakeelAdminPanel/Areas/BlogsModels/Views/Blogs/Index.cshtml
@model IEnumerable<AlwakeelDomainLayer.BlogDomain>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    <a href="/BlogsModels/Blogs/Create" class="btn btn-primary"><i class="fa fa-plus"></i></a>
</p>
<table id="datatable" class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.blogTitleEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.blogTitleAr)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.blogDate)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.ViewsNuber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishBy)
            </th>
         
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.blogTitleEn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.blogTitleAr)
                </td>
               
                <td>
                    @Convert.ToDateTime(item.blogDate).ToString("dd/MM/yyyy")
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ViewsNuber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishBy)
                </td>
                
                <td>
                    
                    <a href=" /BlogsModels/Blogs/Details?Id=@item.blogId" class="btn btn-success"><i class="fa fa-pencil-alt"></i></a>
                    <a href="/BlogsModels/Blogs/Delete?id=@item.blogId" class="btn btn-danger"><i class="fas fa-trash "></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script>

        $(document).ready(function () {
            $('#datatable').DataTable();

        });
    </script>
    }