AlwakeelAdminPanel/Areas/BusinessModels/Controllers/ManagBusinessController.cs
using AlwakeelAdminPanel.Models;
using AlwakeelBusinessLayer.Implementation;
using AlwakeelDomainLayer;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlwakeelAdminPanel.Areas.BusinessModels.Controllers
{
    [Authorize]
    public class ManagBusinessController : Controller
    {
        Business business = new Business();
        UserRole userRole = new UserRole();
        BusinessUsers businessUsers = new BusinessUsers();
        // GET: BusinessModels/ManagBusiness
        public ActionResult Index()
        {
            ViewBag.Titles = "Business";
            List<BusinessDomain> model = new List<BusinessDomain>();
            if (User.IsInRole("Admin"))
            {
                model = business.Get();
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                BusinessDomain bus = business.GetById((int)Buser.BusinessId);
                model.Add(bus);
            }

                return View(model);
        }
        [HttpGet]
       
        public ActionResult Create()
        {
            ViewBag.Titles = "Business";
            ViewBag.userRoles = userRole.GetRole();
            BusinessDomain model = new BusinessDomain();
            model.BusinessSpecial = false;
            ViewBag.Error = null;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(BusinessDomain model)
        {
            ViewBag.Titles = "Business";
          
            ViewBag.userRoles = userRole.GetRole();
            if ( model.BusinessPanelImageFIlle == null)
            {
                return View(model);
            }

            if (model.BusinessLogoFIlle == null)
            {
                return View(model);
            }

            if (business.isHasCompany(model))
            {
                model.BusinessLogo = UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.BusinessLogoFIlle, "logo")), false);
                model.BusinessPanelImage = UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.BusinessPanelImageFIlle, "PanelImage")), false);
                model.BusinessRegistrationRate = DateTime.Now;
                int val = business.AddReturnId(model);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Error = "Sorry, Business already exists";
                return View(model);
            }


          
        }
        [HttpGet]
       // BusinessModels/ManagBusiness/Details?Id=
        public ActionResult Details(int Id)
        {
            ViewBag.Titles = "Business";
            BusinessDomain modle=business.GetById(Id);
            return View(modle);
        }

        [HttpGet]
        public ActionResult Edit(int BId)
        {
            ViewBag.Titles = "Business";
            ViewBag.userRoles = userRole.GetRole();
            BusinessDomain modle = business.GetById(BId);
            return View(modle);
           
        }

        [HttpPost]
        public ActionResult Edit(BusinessDomain model)
        {
            ViewBag.Titles = "Business";
            ViewBag.userRoles = userRole.GetRole();
            if (model.BusinessPanelImageFIlle != null)
            {
                model.BusinessPanelImage = UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.BusinessPanelImageFIlle, "PanelImage")), false);
            }

            if (model.BusinessLogoFIlle != null)
            {
                model.BusinessLogo = UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.BusinessLogoFIlle, "logo")), false);
              
            }
            

            model.BusinessRegistrationRate = DateTime.Now;

            int val = business.Update(model);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            business.Delete(id);
            return RedirectToAction("Index");
        }

        public string AddImage(HttpPostedFileBase File, string Type)
        {
            string fileName = Path.GetFileNameWithoutExtension(File.FileName);
            string extension = Path.GetExtension(File.FileName);
            fileName = Type + DateTime.Now.ToString("yymmssfff") + extension;
            string imgname = "/Image/Business/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/Business"), fileName);
            File.SaveAs(fileName);
            return imgname;
        }
    }
}

AlwakeelAdminPanel/Areas/BusinessModels/Views/ManagBusiness/Create.cshtml
@model AlwakeelDomainLayer.BusinessDomain

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    textarea {
        width: 100%;
    }
</style>

@{
    string err =  ViewBag.Error;
    if (err != null)
    {
        <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <strong> @err !</strong>
        </div>
    }
}

@using (Html.BeginForm("Create", "ManagBusiness", FormMethod.Post, new { enctype = "multipart/form-data" }))
{


    <div class="form-horizontal">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessNameEn, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.BusinessNameEn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessNameEn, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessNameAR, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.BusinessNameAR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessNameAR, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessLocationAr, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.BusinessLocationAr, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessLocationAr, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessLocationEn, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.BusinessLocationEn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessLocationEn, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessLogoFIlle, htmlAttributes: new { @class = "control-label " })
                    <input type="file" id="BusinessLogoFIlle" name="BusinessLogoFIlle" required />
                    <img style="border:1px solid red" id="LogoFIlle" width="60" src="" />
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessPanelImageFIlle, htmlAttributes: new { @class = "control-label " })
                    <input type="file" id="BusinessPanelImageFIlle" name="BusinessPanelImageFIlle" required />
                    <img style="border:1px solid red" id="PanelImageFIlle" width="60" src="" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessAboutEn, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.BusinessAboutEn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessAboutEn, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessAboutAR, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.BusinessAboutAR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessAboutAR, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessType, htmlAttributes: new { @class = "control-label " })
                    <select id="BusinessType" name="BusinessType" class="form-control">
                        @foreach (var item in ViewBag.userRoles)
                        {
                            <option value="@item.Name">@item.Name</option>
                        }
                    </select>
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.BusinessSpecial, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.BusinessSpecial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BusinessSpecial, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-12">

                <div class="form-group" id="Type">
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            var BusinessType = $("#BusinessType").val();
            if (BusinessType == "Agent") {
                AddType();
            }
        });

        $("#BusinessType").change(function () {
            var BusinessType = $("#BusinessType").val();
            if (BusinessType == "Agent") {
                AddType();
            } else {
                $('#Type').empty();
            }
        });


        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#PanelImageFIlle').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#BusinessPanelImageFIlle").change(function () {

            readURL(this);

        });


        function readURL2(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#LogoFIlle').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }


        $("#BusinessLogoFIlle").change(function () {

            readURL2(this);

        });

        function AddType() {

            $('#Type').append(` <label class = "control-label " >Agent Type</label>
                            <select id="AgentType" name="AgentType" class="form-control">
                                 <option value="Battery">Battery</option>
                                <option value="Oil">Oil</option>
                                <option value="Accessories">Accessories</option>
                                <option value="Spareparts">Spareparts</option>
                                <option value="Tires">Tires</option>
                            </select>`);
        }


    </script>
}

AlwakeelAdminPanel/Areas/BusinessModels/Views/ManagBusiness/Details.cshtml
@model AlwakeelDomainLayer.BusinessDomain

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-lg-12">
    <div class="table-responsive">
        <table class="table table-bordered table-striped mb-0">

            <tbody>
                <tr>
                    <th class="text-nowrap" scope="row">Business Name En</th>
                    <td>@Model.BusinessNameEn</td>

                </tr>
                <tr>
                    <th class="text-nowrap" scope="row">Business Name Ar</th>
                    <td>@Model.BusinessNameAR</td>

                </tr>
                <tr>
                    <th class="text-nowrap" scope="row">Registration Data</th>
                    <td colspan="5">@Convert.ToDateTime(Model.BusinessRegistrationRate).ToString("dd/MM/yyyy")</td>
                </tr>
                <tr>
                    <th class="text-nowrap" scope="row">Business Type</th>
                    <td colspan="5"> @Model.BusinessType - @Model.AgentType</td>
                </tr>
                <tr>
                    <th class="text-nowrap" scope="row">Location English Ar</th>
                    <td colspan="5">@Model.BusinessLocationAr</td>
                </tr>
                <tr>
                    <th class="text-nowrap" scope="row">Location English En</th>
                    <td colspan="5">@Model.BusinessLocationEn</td>
                </tr>
                <tr>
                    <th class="text-nowrap" scope="row">About En</th>
                    <td colspan="5"> @Model.BusinessAboutEn</td>
                </tr>

                <tr>
                    <th class="text-nowrap" scope="row">About AR</th>
                    <td colspan="5"> @Model.BusinessAboutAR</td>
                </tr>


                <tr>
                    <th class="text-nowrap" scope="row">Panel Image</th>
                    <td> <img src="@Model.BusinessPanelImage" width="200" height="200" /></td>
                </tr>

                <tr>
                    <th class="text-nowrap" scope="row">Logo</th>
                    <td> <img src="@Model.BusinessLogo" width="200" height="200" /></td>
                </tr>

            </tbody>
        </table>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-12">
        <a href=" /BusinessModels/ManagBusiness/Edit?BId=@Model.BusinessId" class="btn btn-success"><i class="fa fa-pencil-alt"></i></a>
    </div>
</div>

AlwakeelAdminPanel/Areas/BusinessModels/Views/ManagBusiness/Edit.cshtml
@model AlwakeelDomainLayer.BusinessDomain

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    textarea {
        width: 100%;
    }
</style>

@using (Html.BeginForm("Edit", "ManagBusiness", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.BusinessId)
    @Html.HiddenFor(model => model.BusinessPanelImage)
    @Html.HiddenFor(model => model.BusinessLogo)
    @Html.HiddenFor(model => model.active)

<div class="form-horizontal">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessNameEn, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.BusinessNameEn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessNameEn, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessNameAR, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.BusinessNameAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessNameAR, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessLocationAr, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.BusinessLocationAr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessLocationAr, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessLocationEn, htmlAttributes: new { @class = "control-label " })
                @Html.EditorFor(model => model.BusinessLocationEn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessLocationEn, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-12">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessAboutEn, htmlAttributes: new { @class = "control-label " })
                @Html.TextAreaFor(model => model.BusinessAboutEn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessAboutEn, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessAboutAR, htmlAttributes: new { @class = "control-label " })
                @Html.TextAreaFor(model => model.BusinessAboutAR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BusinessAboutAR, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessPanelImageFIlle, htmlAttributes: new { @class = "control-label " })
                <input type="file" id="BusinessPanelImageFIlle" name="BusinessPanelImageFIlle" />
                <img style="border:1px solid red" id="PanelImageFIlle" width="60" src="@Model.BusinessPanelImage" />
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessLogoFIlle, htmlAttributes: new { @class = "control-label " })
                <input type="file" id="BusinessLogoFIlle" name="BusinessLogoFIlle" />
                <img style="border:1px solid red" id="LogoFIlle" width="60" src="@Model.BusinessLogo" />
            </div>
        </div>
    </div>
    @{
        if (Model.BusinessType == "Admin")
        {
            @Html.HiddenFor(model => model.BusinessType)
            @Html.HiddenFor(model => model.BusinessSpecial)
            @Html.HiddenFor(model => model.AgentType)
        }
        else
        {

            if (User.IsInRole("Admin"))
            {
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.BusinessType, htmlAttributes: new { @class = "control-label " })
                            <select id="BusinessType" name="BusinessType" class="form-control">
                                @foreach (var item in ViewBag.userRoles)
                                {
                                    <option value="@item.Name">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group" id="Type">
                        </div>
                    </div>
                </div>
            }
            else
            {
                @Html.HiddenFor(model => model.BusinessType)
                @Html.HiddenFor(model => model.BusinessSpecial)
                @Html.HiddenFor(model => model.AgentType)
            }

        }


    }
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-primary" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            var BusinessType = $("#BusinessType").val();
            if (BusinessType == "Agent") {
                AddType();
            }
        });
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#PanelImageFIlle').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#BusinessPanelImageFIlle").change(function () {

            readURL(this);

        });


        $("#BusinessType").change(function () {
            var BusinessType = $("#BusinessType").val();
            if (BusinessType == "Agent") {
                AddType();
            } else {
                $('#Type').empty();
            }
        });

        function readURL2(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#LogoFIlle').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }


        $("#BusinessLogoFIlle").change(function () {

            readURL2(this);

        });


        function AddType() {

            $('#Type').append(` <label class = "control-label " >Agent Type</label>
                                <select id="AgentType" name="AgentType" class="form-control">
                                     <option value="Battery">Battery</option>
                                    <option value="Oil">Oil</option>
                                    <option value="Accessories">Accessories</option>
                                    <option value="Spareparts">Spareparts</option>
                                    <option value="Tires">Tires</option>
                                </select>`);
        }

    </script>
}

AlwakeelAdminPanel/Areas/BusinessModels/Views/ManagBusiness/Index.cshtml
@model IEnumerable<AlwakeelDomainLayer.BusinessDomain>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (User.IsInRole("Admin"))
{
    <p>
        <a href="/BusinessModels/ManagBusiness/Create" class="btn btn-primary"><i class="fa fa-plus"></i></a>
    </p>
}

<table id="datatable" class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.BusinessNameEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessNameAR)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.BusinessLogo)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.BusinessType)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.BusinessNameEn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessNameAR)
                </td>
                <td>
                    <img src="@item.BusinessLogo" width="40" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BusinessType)-  @Html.DisplayFor(modelItem => item.AgentType)
                </td>

                <td>
                    <a href=" /Account/Register?BusinessId=@item.BusinessId&RoleName=@item.BusinessType" class="btn btn-primary"><i class="fas fa-user-plus"></i></a>
                    <a href=" /BusinessModels/ManagBusiness/Details?Id=@item.BusinessId" class="btn btn-success"><i class="fa fa-pencil-alt"></i></a>

                    @if (User.IsInRole("Admin"))
                    {
                        <a href="/BusinessModels/ManagBusiness/Delete?id=@item.BusinessId" class="btn btn-danger"><i class="fas fa-trash "></i></a>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable();

        });
    </script>
}