AlwakeelAdminPanel/Areas/BusinessModels/Controllers/BusinessProductsController.cs
using AlwakeelAdminPanel.Models;
using AlwakeelBusinessLayer.Implementation;
using AlwakeelDomainLayer;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlwakeelAdminPanel.Areas.BusinessModels.Controllers
{

    [Authorize]
    public class BusinessProductsController : Controller
    {
        BusinessProduct BP = new BusinessProduct();
        Business business = new Business();
        BusinessUsers businessUsers = new BusinessUsers();
        // GET: BusinessModels/BusinessProducts
        public ActionResult Index()
        {

            ViewBag.Titles = "Business Products";
            List<BusinessProductDomain> model = new List<BusinessProductDomain>();
            if (User.IsInRole("Admin"))
            {
                model = BP.Get();
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                model = BP.GetByBusinessId((int)Buser.BusinessId);
            }

            return View(model);
        }

        // GET: BusinessModels/BusinessProducts/Create
        public ActionResult Create()
        {
            ViewBag.Titles = "Business Products";
            if (User.IsInRole("Admin"))
            {
                List<BusinessDomain> BModel = business.Get();
                ViewBag.BModel = BModel.ToList();
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                BusinessDomain BModel = business.GetById((int)Buser.BusinessId);
                ViewBag.BModel = BModel;
            }


            return View();
        }

        // POST: BusinessModels/BusinessProducts/Create
        [HttpPost]
        public ActionResult Create(BusinessProductDomain model)
        {
            ViewBag.Titles = "Business Products";
            if (User.IsInRole("Admin"))
            {
                List<BusinessDomain> BModel = business.Get();
                ViewBag.BModel = BModel.ToList();
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                BusinessDomain BModel = business.GetById((int)Buser.BusinessId);
                ViewBag.BModel = BModel;
            }
            try
            {
                if (model.PimageUrlFile == null)
                {
                    return View(model);
                }


                model.PimageUrl = UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.PimageUrlFile, "Pimage")), false);
                BP.Add(model);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            ViewBag.Titles = "Business Products";
            if (User.IsInRole("Admin"))
            {
                List<BusinessDomain> BModel = business.Get();
                ViewBag.BModel = BModel.ToList();
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                BusinessDomain BModel = business.GetById((int)Buser.BusinessId);
                ViewBag.BModel = BModel;
            }
            BusinessProductDomain model = BP.GetByPid(Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(BusinessProductDomain model)
        {
            ViewBag.Titles = "Business Products";
            if (User.IsInRole("Admin"))
            {
                List<BusinessDomain> BModel = business.Get();
                ViewBag.BModel = BModel.ToList();
            }
            else
            {
                string UserId = User.Identity.GetUserId();
                BusinessUserDomain Buser = businessUsers.Get(UserId);
                BusinessDomain BModel = business.GetById((int)Buser.BusinessId);
                ViewBag.BModel = BModel;
            }
            try
            {
                if (model.PimageUrlFile != null)
                {
                    model.PimageUrl = UplodImage.ResolveServerUrl(VirtualPathUtility.ToAbsolute(AddImage(model.PimageUrlFile, "Pimage")), false);
                }


              
                BP.Update(model);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: BusinessModels/BusinessProducts/Delete/5
        public ActionResult Delete(int id)
        {
            BP.Delete(id);
            return RedirectToAction("Index");
        }

        // BusinessModels/BusinessProducts/GetProductsType?BId=
        public JsonResult GetProductsType(int BId)
        {
            BusinessDomain BModel = business.GetById(BId);
            if (BModel.BusinessType.Contains("Company") || BModel.BusinessType.Contains("Admin"))
            {
                List<ProductsType> model = new List<ProductsType>() {
                   new ProductsType{PName="Tires" },
                    new ProductsType{PName="Battery" },
                    new ProductsType{PName="Oil" }
                };
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            else if (BModel.BusinessType.Contains("Agens"))
            {
                List<ProductsType> model = new List<ProductsType>() {
                  new ProductsType{PName=BModel.AgentType }
                };
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            else
            {
                List<ProductsType> model = new List<ProductsType>() {
                  new ProductsType{PName=BModel.BusinessType }
                };
                return Json(model, JsonRequestBehavior.AllowGet);
            }
        }
        public string AddImage(HttpPostedFileBase File, string Type)
        {
            string fileName = Path.GetFileNameWithoutExtension(File.FileName);
            string extension = Path.GetExtension(File.FileName);
            fileName = Type + DateTime.Now.ToString("yymmssfff") + extension;
            string imgname = "/Image/Business/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/Business"), fileName);
            File.SaveAs(fileName);
            return imgname;
        }
    }
}

AlwakeelAdminPanel/Areas/BusinessModels/Views/BusinessProducts/Create.cshtml
@model AlwakeelDomainLayer.BusinessProductDomain

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "BusinessProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(model => model.id)
    <div class="form-horizontal">
        @if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                <label class="control-label">Business</label>
                <select id="BusinessId" name="BusinessId" class="form-control">
                    @foreach (var item in ViewBag.BModel)
                    {
                        <option value="@item.BusinessId">@item.BusinessNameEn - @item.BusinessNameAR</option>
                    }
                </select>
            </div>
        }
        else
        {
            <input id="BusinessId" name="BusinessId" type="hidden" value="@ViewBag.BModel.BusinessId" />
        }
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PNameEN, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.PNameEN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PNameEN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PNameAR, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.PNameAR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PNameAR, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DescribeAR, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.DescribeAR, new { htmlAttributes = new { @class = "form-control",@style="width:100%;" } })
                    @Html.ValidationMessageFor(model => model.DescribeAR, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DescribeEN, htmlAttributes: new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.DescribeEN, new { htmlAttributes = new { @class = "form-control",@style="width:100%;" } })
                    @Html.ValidationMessageFor(model => model.DescribeEN, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label class="control-label">Product Type</label>
                    <select id="ProductType" name="ProductType" class="form-control">
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PimageUrlFile, htmlAttributes: new { @class = "control-label " })
            <input id="PimageUrlFile" name="PimageUrlFile" type="file" required />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            var BusinessId = $("#BusinessId").val();
            GetProductsType(BusinessId);
        });

        $("#BusinessId").change(function () {
            var BusinessId = $("#BusinessId").val();
            GetProductsType(BusinessId);
        });


        var GetProductsType = function (BrandId) {
            $("#ProductType").empty();
            $.get("/BusinessModels/BusinessProducts/GetProductsType?BId=" + BrandId, function (data, status) {
                for (var i = 0; i < data.length; i++) {
                    $('#ProductType').append('<option value="' + data[i].PName + '">' + data[i].PName + '</option>');
                }
            });

        };

    </script>
}

AlwakeelAdminPanel/Areas/BusinessModels/Views/BusinessProducts/Edit.cshtml
@model AlwakeelDomainLayer.BusinessProductDomain

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "BusinessProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.PimageUrl)
    <div class="form-horizontal">
        @if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                <label class="control-label">Business</label>
                <select id="BusinessId" name="BusinessId" class="form-control">
                    @foreach (var item in ViewBag.BModel)
                    {
                        <option value="@item.BusinessId">@item.BusinessNameEn - @item.BusinessNameAR</option>
                    }
                </select>
            </div>
        }
        else
        {
            <input id="BusinessId" name="BusinessId" type="hidden" value="@ViewBag.BModel.BusinessId" />
        }
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PNameEN, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.PNameEN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PNameEN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.PNameAR, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.PNameAR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PNameAR, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DescribeAR, htmlAttributes: new { @class = "control-label " })
                    @Html.TextAreaFor(model => model.DescribeAR, new { htmlAttributes = new { @class = "form-control", @style = "width:100%;" } })
                    @Html.ValidationMessageFor(model => model.DescribeAR, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.DescribeEN, htmlAttributes: new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.DescribeEN, new { htmlAttributes = new { @class = "form-control", @style = "width:100%;" } })
                    @Html.ValidationMessageFor(model => model.DescribeEN, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label class="control-label">Product Type</label>
                    <select id="ProductType" name="ProductType" class="form-control">
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PimageUrlFile, htmlAttributes: new { @class = "control-label " })
            <input id="PimageUrlFile" name="PimageUrlFile" type="file" />
            <img src="@Model.PimageUrl" width="40" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            var BusinessId = $("#BusinessId").val();
            GetProductsType(BusinessId);
        });

        $("#BusinessId").change(function () {
            var BusinessId = $("#BusinessId").val();
            GetProductsType(BusinessId);
        });


        var GetProductsType = function (BrandId) {
            $("#ProductType").empty();
            $.get("/BusinessModels/BusinessProducts/GetProductsType?BId=" + BrandId, function (data, status) {
                for (var i = 0; i < data.length; i++) {
                    $('#ProductType').append('<option value="' + data[i].PName + '">' + data[i].PName + '</option>');
                }
            });

        };

    </script>
}

AlwakeelAdminPanel/Areas/BusinessModels/Views/BusinessProducts/Index.cshtml
@model IEnumerable<AlwakeelDomainLayer.BusinessProductDomain>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<p>
    <a href="/BusinessModels/BusinessProducts/Create" class="btn btn-primary" ><i class="fa fa-plus"></i></a>
</p>
<table id="datatable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PNameEN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PNameAR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PimageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductType)
            </th>
            <th>
                Business Name
            </th>

            <th></th>
        </tr>
    </thead>
    
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PNameEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PNameAR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <img src="@item.PimageUrl" width="40" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductType)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BusinessNameEn)
            </td>

            <td>
                <a href=" /BusinessModels/BusinessProducts/Edit?Id=@item.id" class="btn btn-warning"><i class="fa fa-pencil-alt"></i></a>
                <a href="/BusinessModels/BusinessProducts/Delete?id=@item.id" class="btn btn-danger"><i class="fas fa-trash "></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable();
        });
    </script>
}